  export const users = [
  {
    id: 1,
    name: "Rahul Sharma",
    email: "rahul@example.com",
    age: 25,
    city: "Delhi",
    role: "Frontend Developer",
  },
  {
    id: 2,
    name: "Priya Singh",
    email: "priya@example.com",
    age: 28,
    city: "Mumbai",
    role: "Backend Developer",
  },
  {
    id: 3,
    name: "Amit Kumar",
    email: "amit@example.com",
    age: 30,
    city: "Patna",
    role: "Full Stack Developer",
  },
  {
    id: 4,
    name: "Sneha Verma",
    email: "sneha@example.com",
    age: 24,
    city: "Bangalore",
    role: "UI Designer",
  },
  {
    id: 5,
    name: "Rohit Gupta",
    email: "rohit@example.com",
    age: 27,
    city: "Lucknow",
    role: "QA Engineer",
  },
  {
    id: 6,
    name: "Neha Patel",
    email: "neha@example.com",
    age: 29,
    city: "Ahmedabad",
    role: "HR",
  },
  {
    id: 7,
    name: "Arjun Yadav",
    email: "arjun@example.com",
    age: 31,
    city: "Jaipur",
    role: "DevOps Engineer",
  },
  {
    id: 8,
    name: "Pooja Mishra",
    email: "pooja@example.com",
    age: 26,
    city: "Indore",
    role: "Business Analyst",
  },
  {
    id: 9,
    name: "Karan Mehta",
    email: "karan@example.com",
    age: 32,
    city: "Pune",
    role: "Product Manager",
  },
  {
    id: 10,
    name: "Anjali Roy",
    email: "anjali@example.com",
    age: 23,
    city: "Kolkata",
    role: "Frontend Developer",
  },
  {
    id: 11,
    name: "Vikas Chauhan",
    email: "vikas@example.com",
    age: 35,
    city: "Chandigarh",
    role: "Tech Lead",
  },
  {
    id: 12,
    name: "Meera Nair",
    email: "meera@example.com",
    age: 27,
    city: "Kochi",
    role: "UI/UX Designer",
  },
  {
    id: 13,
    name: "Sahil Khan",
    email: "sahil@example.com",
    age: 29,
    city: "Hyderabad",
    role: "Backend Developer",
  },
  {
    id: 14,
    name: "Riya Das",
    email: "riya@example.com",
    age: 22,
    city: "Guwahati",
    role: "Intern",
  },
  {
    id: 15,
    name: "Deepak Soni",
    email: "deepak@example.com",
    age: 34,
    city: "Bhopal",
    role: "Project Manager",
  },
  {
    id: 16,
    name: "Komal Jain",
    email: "komal@example.com",
    age: 26,
    city: "Surat",
    role: "QA Engineer",
  },
  {
    id: 17,
    name: "Manish Tiwari",
    email: "manish@example.com",
    age: 33,
    city: "Kanpur",
    role: "Data Analyst",
  },
  {
    id: 18,
    name: "Shweta Rao",
    email: "shweta@example.com",
    age: 28,
    city: "Nagpur",
    role: "HR",
  },
  {
    id: 19,
    name: "Nitin Agarwal",
    email: "nitin@example.com",
    age: 30,
    city: "Noida",
    role: "Software Engineer",
  },
  {
    id: 20,
    name: "Aisha Khan",
    email: "aisha@example.com",
    age: 24,
    city: "Chennai",
    role: "Frontend Developer",
  },
];
